version: '3.7'

services:
    database:
        build: ./bdd
        container_name: postgres-bdd
        volumes:
          - /data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        networks: 
            - app-network

    backend:
        build: ./api
        ports: 
            - 8080:8080
        networks: 
            - app-network
        depends_on: 
            - database

    httpd:
        build: ./web
        ports: 
            - 5000:80
        networks: 
            - app-network
        depends_on: 
            - backend

networks:
    app-network:
